#cloud-config
package_update: true
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - jq

disk_setup:
  /dev/disk/azure/scsi1/lun0:
    table_type: gpt
    layout: True
    overwrite: False

fs_setup:
  - device: /dev/disk/azure/scsi1/lun0
    partition: 1
    filesystem: ext4

mounts:
    - ["/dev/disk/azure/scsi1/lun0-part1", "/data", auto, "defaults,nofail"]

# create the docker group
groups:
  - docker: [azureuser]

runcmd:
  # Install Docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io
  - systemctl start docker
  - systemctl enable docker
  - usermod -aG docker azureuser
  # Install Docker Compose
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  # Install Azure CLI
  - curl -sL https://aka.ms/InstallAzureCLIDeb | bash
  - az login --identity
  # Clone git repo
  - cd /data
  - su azureuser
  - git clone https://github.com/JKomskis/AzureTemplates.git
  - cd AzureTemplates
  - ./matomo/create_env_file.sh
  # Run containers
  - docker network create frontend
  - cd matomo
  - docker-compose up -d
  - cd ../traefik
  - docker compose up -d

