version: '3'

services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    command: --max-allowed-packet=64MB
    restart: always
    networks:
      - backend
    volumes:
      - ./mysql_data:/var/lib/mysql
    env_file:
      - ./.env

  matomo:
    image: matomo:fpm-alpine
    container_name: matomo
    restart: always
    networks:
      - backend
    volumes:
    #  - ./matomo_config:/var/www/html/config:rw
    #  - ./matomo_logs:/var/www/html/logs
      - ./matomo_data:/var/www/html
    env_file:
      - ./.env

  matomo-web:
    image: nginx:alpine
    container_name: matomo-web
    restart: always
    networks:
      - frontend
      - backend
    volumes:
      - ./matomo_data:/var/www/html:ro
      # see https://github.com/matomo-org/matomo-nginx
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.matomo.rule=Host(`analytics.jkomskis.com`)"
      - "traefik.http.routers.matomo.entrypoints=websecure"
      - "traefik.http.routers.matomo.tls.certresolver=myhttpchallenge"

networks:
  frontend:
    external: true
  backend:
    driver: bridge